from glyphNameFormatter.data import name2unicode_AGD
from defcon import Font

font = Font("Roman/Amstelvar-Roman-opsz-min.ufo")

composites = {
	"Aacute": "A+acute.uc",
	"aacute": "a+acute",
	"Abreve": "A+breve.uc",
	"abreve": "a+breve",
	"Abreveacute": "A+breve_acute.uc",
	"abreveacute": "a+breve_acute",
	"Abrevedotbelow": "A+breve.uc+dotbelow",
	"abrevedotbelow": "a+breve+dotbelow",
	"Abrevegrave": "A+breve_grave.uc",
	"abrevegrave": "a+breve_grave",
	"Abrevehookabove": "A+breve_hookabove.uc",
	"abrevehookabove": "a+breve_hookabove",
	"Abrevetilde": "A+breve_tilde.uc",
	"abrevetilde": "a+breve_tilde",
	"Acircumflex": "A+circumflex.uc",
	"acircumflex": "a+circumflex",
	"Acircumflexacute": "A+circumflex_acute.uc",
	"acircumflexacute": "a+circumflex_acute",
	"Acircumflexdotbelow": "A+circumflex.uc+dotbelow",
	"acircumflexdotbelow": "a+circumflex+dotbelow",
	"Acircumflexgrave": "A+circumflex_grave.uc",
	"acircumflexgrave": "a+circumflex_grave",
	"Acircumflexhookabove": "A+circumflex_hookabove.uc",
	"acircumflexhookabove": "a+circumflex_hookabove",
	"Acircumflextilde": "A+circumflex_tilde.uc",
	"acircumflextilde": "a+circumflex_tilde",
	"Adblgrave": "A+dblgrave.uc",
	"adblgrave": "a+dblgrave",
	"Adieresis": "A+dieresis.uc",
	"adieresis": "a+dieresis",
	"Adotbelow": "A+dotbelow",
	"adotbelow": "a+dotbelow",
	"AEacute": "AE+acute.uc",
	"aeacute": "ae+acute",
	"Agrave": "A+grave.uc",
	"agrave": "a+grave",
	"Ahookabove": "A+hookabove.uc",
	"ahookabove": "a+hookabove",
	"Ainvertedbreve": "A+breveinverted.uc",
	"ainvertedbreve": "a+breveinverted",
	"Amacron": "A+macron.uc",
	"amacron": "a+macron",
	"Aogonek": "A+ogonek",
	"aogonek": "a+ogonek",
	"Aring": "A+ring.uc",
	"aring": "a+ring",
	"Aringacute": "A+ring_acute.uc",
	"aringacute": "a+ring_acute",
	"Atilde": "A+tilde.uc",
	"atilde": "a+tilde",
	"Cacute": "C+acute.uc",
	"cacute": "c+acute",
	"Ccaron": "C+caron.uc",
	"ccaron": "c+caron",
	"Ccedilla": "C+cedilla.uc",
	"ccedilla": "c+cedilla",
	"Ccircumflex": "C+circumflex.uc",
	"ccircumflex": "c+circumflex",
	"Cdotaccent": "C+dotaccent.uc",
	"cdotaccent": "c+dotaccent",
	"dcaron": "d+caron.alt",
	"Dcaron": "D+caron.uc",
	"Eacute": "E+acute.uc",
	"eacute": "e+acute",
	"Ebreve": "E+breve.uc",
	"ebreve": "e+breve",
	"Ecaron": "E+caron.uc",
	"ecaron": "e+caron",
	"Ecircumflex": "E+circumflex.uc",
	"ecircumflex": "e+circumflex",
	"Ecircumflexacute": "E+circumflex_acute.uc",
	"ecircumflexacute": "e+circumflex_acute",
	"Ecircumflexdotbelow": "E+circumflex.uc+dotbelow",
	"ecircumflexdotbelow": "e+circumflex+dotbelow",
	"Ecircumflexgrave": "E+circumflex_grave.uc",
	"ecircumflexgrave": "e+circumflex_grave",
	"Ecircumflexhookabove": "E+circumflex_hookabove.uc",
	"ecircumflexhookabove": "e+circumflex_hookabove",
	"Ecircumflextilde": "E+circumflex_tilde.uc",
	"ecircumflextilde": "e+circumflex_tilde",
	"Edblgrave": "E+dblgrave.uc",
	"edblgrave": "e+dblgrave",
	"Edieresis": "E+dieresis.uc",
	"edieresis": "e+dieresis",
	"Edotaccent": "E+dotaccent.uc",
	"edotaccent": "e+dotaccent",
	"Edotbelow": "E+dotbelow",
	"edotbelow": "e+dotbelow",
	"Egrave": "E+grave.uc",
	"egrave": "e+grave",
	"Ehookabove": "E+hookabove.uc",
	"ehookabove": "e+hookabove",
	"Einvertedbreve": "E+breveinverted.uc",
	"einvertedbreve": "e+breveinverted",
	"Emacron": "E+macron.uc",
	"emacron": "e+macron",
	"Eogonek": "E+ogonek",
	"eogonek": "e+ogonek",
	"Etilde": "E+tilde.uc",
	"etilde": "e+tilde",
	"Gbreve": "G+breve.uc",
	"gbreve": "g+breve",
	"Gcaron": "G+caron.uc",
	"gcaron": "g+caron",
	"Gcircumflex": "G+circumflex.uc",
	"gcircumflex": "g+circumflex",
	"Gcommaaccent": "G+commaaccent",
	"gcommaaccent": "g+commaturnedabove",
	"Gdotaccent": "G+dotaccent.uc",
	"gdotaccent": "g+dotaccent",
	"Hcircumflex": "H+circumflex.uc",
	"hcircumflex": "h+circumflex",
	"Iacute": "I+acute.uc",
	"iacute": "idotless+acute",
	"Ibreve": "I+breve.uc",
	"ibreve": "idotless+breve",
	"Icircumflex": "I+circumflex.uc",
	"icircumflex": "idotless+circumflex",
	"Idblgrave": "I+dblgrave.uc",
	"idblgrave": "idotless+dblgrave",
	"Idieresis": "I+dieresis.uc",
	"idieresis": "idotless+dieresis",
	"Idotaccent": "I+dotaccent.uc",
	"idotaccent": "idotless+dotaccent",
	"Idotbelow": "I+dotbelow",
	"idotbelow": "i+dotbelow",
	"Igrave": "I+grave.uc",
	"igrave": "idotless+grave",
	"Ihookabove": "I+hookabove.uc",
	"ihookabove": "idotless+hookabove",
	"Iinvertedbreve": "I+breveinverted.uc",
	"iinvertedbreve": "idotless+breveinverted",
	"Imacron": "I+macron.uc",
	"imacron": "idotless+macron",
	"Iogonek": "I+ogonek",
	"iogonek": "i+ogonek",
	"Itilde": "I+tilde.uc",
	"itilde": "idotless+tilde",
	"Jcircumflex": "J+circumflex.uc",
	"jcircumflex": "jdotless+circumflex",
	"Kcommaaccent": "K+commaaccent",
	"kcommaaccent": "k+commaaccent",
	"Lacute": "L+acute.uc",
	"lacute": "l+acute",
	"Lcaron": "L+caron.alt",
	"lcaron": "l+caron.alt",
	"Lcommaaccent": "L+commaaccent",
	"lcommaaccent": "l+commaaccent",
	"Ldot": "L+dotaccent",
	"ldot": "l+dotaccent",
	"Nacute": "N+acute.uc",
	"nacute": "n+acute",
	"Ncaron": "N+caron.uc",
	"ncaron": "n+caron",
	"Ncommaaccent": "N+commaaccent",
	"ncommaaccent": "n+commaaccent",
	"Ntilde": "N+tilde.uc",
	"ntilde": "n+tilde",
	"Oacute": "O+acute.uc",
	"oacute": "o+acute",
	"Obreve": "O+breve.uc",
	"obreve": "o+breve",
	"Ocircumflex": "O+circumflex.uc",
	"ocircumflex": "o+circumflex",
	"Ocircumflexacute": "O+circumflex_acute.uc",
	"ocircumflexacute": "o+circumflex_acute",
	"Ocircumflexdotbelow": "O+circumflex.uc+dotbelow",
	"ocircumflexdotbelow": "o+circumflex+dotbelow",
	"Ocircumflexgrave": "O+circumflex_grave.uc",
	"ocircumflexgrave": "o+circumflex_grave",
	"Ocircumflexhookabove": "O+circumflex_hookabove.uc",
	"ocircumflexhookabove": "o+circumflex_hookabove",
	"Ocircumflextilde": "O+circumflex_tilde.uc",
	"ocircumflextilde": "o+circumflex_tilde",
	"Odblgrave": "O+dblgrave.uc",
	"odblgrave": "o+dblgrave",
	"Odieresis": "O+dieresis.uc",
	"odieresis": "o+dieresis",
	"Odieresismacron": "O+dieresis_macron.uc",
	"odieresismacron": "o+dieresis_macron",
	"Odotaccentmacron": "O+dotaccent_macron.uc",
	"odotaccentmacron": "o+dotaccent_macron",
	"Odotbelow": "O+dotbelow",
	"odotbelow": "o+dotbelow",
	"Ograve": "O+grave.uc",
	"ograve": "o+grave",
	"Ohookabove": "O+hookabove.uc",
	"ohookabove": "o+hookabove",
	"Ohorn": "O+horn.uc",
	"ohorn": "o+horn",
	"Ohornacute": "O+horn.uc+acute.uc",
	"ohornacute": "o+horn+acute",
	"Ohorndotbelow": "O+horn.uc+dotbelow",
	"ohorndotbelow": "o+horn+dotbelow",
	"Ohorngrave": "O+horn.uc+grave.uc",
	"ohorngrave": "o+horn+grave",
	"Ohornhookabove": "O+horn.uc+hookabove.uc",
	"ohornhookabove": "o+horn+hookabove",
	"Ohorntilde": "O+horn.uc+tilde.uc",
	"ohorntilde": "o+horn+tilde",
	"Ohungarumlaut": "O+hungarumlaut.uc",
	"ohungarumlaut": "o+hungarumlaut",
	"Oinvertedbreve": "O+breveinverted.uc",
	"oinvertedbreve": "o+breveinverted",
	"Omacron": "O+macron.uc",
	"omacron": "o+macron",
	"Oogonek": "O+ogonek",
	"oogonek": "o+ogonek",
	"Oslashacute": "Oslash+acute.uc",
	"oslashacute": "oslash+acute",
	"Otilde": "O+tilde.uc",
	"otilde": "o+tilde",
	"Otildemacron": "O+tilde_macron.uc",
	"otildemacron": "o+tilde_macron",
	"Racute": "R+acute.uc",
	"racute": "r+acute",
	"Rcaron": "R+caron.uc",
	"rcaron": "r+caron",
	"Rcommaaccent": "R+commaaccent",
	"rcommaaccent": "r+commaaccent",
	"Rdblgrave": "R+dblgrave.uc",
	"rdblgrave": "r+dblgrave",
	"Rinvertedbreve": "R+breveinverted.uc",
	"rinvertedbreve": "r+breveinverted",
	"Sacute": "S+acute.uc",
	"sacute": "s+acute",
	"Scaron": "S+caron.uc",
	"scaron": "s+caron",
	"Scedilla": "S+cedilla",
	"scedilla": "s+cedilla",
	"Scircumflex": "S+circumflex.uc",
	"scircumflex": "s+circumflex",
	"Scommaaccent": "S+commaaccent",
	"scommaaccent": "s+commaaccent",
	"tcaron": "t+caron.alt",
	"Tcaron": "T+caron.uc",
	"Tcedilla": "T+cedilla",
	"tcedilla": "t+cedilla",
	"Tcommaaccent": "T+commaaccent",
	"tcommaaccent": "t+commaaccent",
	"Uacute": "U+acute.uc",
	"uacute": "u+acute",
	"Ubreve": "U+breve.uc",
	"ubreve": "u+breve",
	"Ucircumflex": "U+circumflex.uc",
	"ucircumflex": "u+circumflex",
	"Udblgrave": "U+dblgrave.uc",
	"udblgrave": "u+dblgrave",
	"Udieresis": "U+dieresis.uc",
	"udieresis": "u+dieresis",
	"Udotbelow": "U+dotbelow",
	"udotbelow": "u+dotbelow",
	"Ugrave": "U+grave.uc",
	"ugrave": "u+grave",
	"Uhookabove": "U+hookabove.uc",
	"uhookabove": "u+hookabove",
	"Uhorn": "hornU+horn.uc",
	"uhorn": "hornu+horn",
	"Uhornacute": "hornU+horn.uc+acute.uc",
	"uhornacute": "hornu+horn+acute",
	"Uhorndotbelow": "hornU+horn.uc+dotbelow",
	"uhorndotbelow": "hornu+horn+dotbelow",
	"Uhorngrave": "hornU+horn.uc+grave.uc",
	"uhorngrave": "hornu+horn+grave",
	"Uhornhookabove": "hornU+horn.uc+hookabove.uc",
	"uhornhookabove": "hornu+horn+hookabove",
	"Uhorntilde": "hornU+horn.uc+tilde.uc",
	"uhorntilde": "hornu+horn+tilde",
	"Uhungarumlaut": "U+hungarumlaut.uc",
	"uhungarumlaut": "u+hungarumlaut",
	"Uinvertedbreve": "U+breveinverted.uc",
	"uinvertedbreve": "u+breveinverted",
	"Umacron": "U+macron.uc",
	"umacron": "u+macron",
	"Uogonek": "U+ogonek",
	"uogonek": "u+ogonek",
	"Uring": "U+ring.uc",
	"uring": "u+ring",
	"Utilde": "U+tilde.uc",
	"utilde": "u+tilde",
	"Wacute": "W+acute.uc",
	"wacute": "w+acute",
	"Wcircumflex": "W+circumflex.uc",
	"wcircumflex": "w+circumflex",
	"Wdieresis": "W+dieresis.uc",
	"wdieresis": "w+dieresis",
	"Wgrave": "W+grave.uc",
	"wgrave": "w+grave",
	"Yacute": "Y+acute.uc",
	"yacute": "y+acute",
	"Ycircumflex": "Y+circumflex.uc",
	"ycircumflex": "y+circumflex",
	"Ydieresis": "Y+dieresis.uc",
	"ydieresis": "y+dieresis",
	"Ydotbelow": "Y+dotbelow",
	"ydotbelow": "y+dotbelow",
	"Ygrave": "Y+grave.uc",
	"ygrave": "y+grave",
	"Yhookabove": "Y+hookabove.uc",
	"yhookabove": "y+hookabove",
	"Ymacron": "Y+macron.uc",
	"ymacron": "y+macron",
	"Ytilde": "Y+tilde.uc",
	"ytilde": "y+tilde",
	"Zacute": "Z+acute.uc",
	"zacute": "z+acute",
	"Zcaron": "Z+caron.uc",
	"zcaron": "z+caron",
	"Zdotaccent": "Z+dotaccent.uc",
	"zdotaccent": "z+dotaccent",
}

def buildComposites(font, composites):
	for glyphName in composites.keys():
		font.newGlyph(glyphName)
		composite = font[glyphName]
		#composite.unicode = name2unicode_AGD[glyphName]
		
		value = composites[glyphName]
		items = value.split("+")
		base = items[0]
		items = items[1:]
	
		component = composite.instantiateComponent()
		component.baseGlyph = base
		baseGlyph = font[base]
		composite.width = baseGlyph.width
		composite.appendComponent(component)
		
		baseOffset = baseGlyph.width/2
		for item in items:
			component = composite.instantiateComponent()
			component.baseGlyph = item
			itemGlyph = font[item]
			itemOffset = itemGlyph.width/2
			# get baseGlyph center as anchor, minus itemGlyph center
			offsetX = baseOffset-itemOffset
			component.move((offsetX, 0))
			composite.appendComponent(component)
		composite.lib['com.typemytype.robofont.mark'] = [0, 0, 0, 0.5] # grey
	font.save()
	
buildComposites(font, composites)
