font = CurrentFont()

composites = {
	"Aacute": "A+acute.uc@top",
	"aacute": "a+acute@top",
	"Abreve": "A+breve.uc@top",
	"abreve": "a+breve@top",
	"Abreveacute": "A+breve_acute.uc@top",
	"abreveacute": "a+breve_acute@top",
	"Abrevedotbelow": "A+breve.uc@top+dotbelow@bottom",
	"abrevedotbelow": "a+breve@top+dotbelow@bottom",
	"Abrevegrave": "A+breve_grave.uc@top",
	"abrevegrave": "a+breve_grave@top",
	"Abrevehookabove": "A+breve_hookabove.uc@top",
	"abrevehookabove": "a+breve_hookabove@top",
	"Abrevetilde": "A+breve_tilde.uc@top",
	"abrevetilde": "a+breve_tilde@top",
	"Acircumflex": "A+circumflex.uc@top",
	"acircumflex": "a+circumflex@top",
	"Acircumflexacute": "A+circumflex_acute.uc@top",
	"acircumflexacute": "a+circumflex_acute@top",
	"Acircumflexdotbelow": "A+circumflex.uc@top+dotbelow@bottom",
	"acircumflexdotbelow": "a+circumflex@top+dotbelow@bottom",
	"Acircumflexgrave": "A+circumflex_grave.uc@top",
	"acircumflexgrave": "a+circumflex_grave@top",
	"Acircumflexhookabove": "A+circumflex_hookabove.uc@top",
	"acircumflexhookabove": "a+circumflex_hookabove@top",
	"Acircumflextilde": "A+circumflex_tilde.uc@top",
	"acircumflextilde": "a+circumflex_tilde@top",
	"Adblgrave": "A+dblgrave.uc@top",
	"adblgrave": "a+dblgrave@top",
	"Adieresis": "A+dieresis.uc@top",
	"adieresis": "a+dieresis@top",
	"Adotbelow": "A+dotbelow.uc@bottom",
	"adotbelow": "a+dotbelow@bottom",
	"AEacute": "AE+acute.uc@top",
	"aeacute": "ae+acute@top",
	"Agrave": "A+grave.uc@top",
	"agrave": "a+grave@top",
	"Ahookabove": "A+hookabove.uc@top",
	"ahookabove": "a+hookabove@top",
	"Ainvertedbreve": "A+breveinverted.uc@top",
	"ainvertedbreve": "a+breveinverted@top",
	"Amacron": "A+macron.uc@top",
	"amacron": "a+macron@top",
	#"Aogonek": "A+ogonek.uc",
	#"aogonek": "a+ogonek",
	"Aring": "A+ring.uc@top",
	"aring": "a+ring@top",
	"Aringacute": "A+ring_acute.uc@top",
	"aringacute": "a+ring_acute@top",
	"Atilde": "A+tilde.uc@top",
	"atilde": "a+tilde@top",
	"Cacute": "C+acute.uc@top",
	"cacute": "c+acute@top",
	"Ccaron": "C+caron.uc@top",
	"ccaron": "c+caron@top",
	"Ccedilla": "C+cedilla.uc@bottom",
	"ccedilla": "c+cedilla@bottom",
	"Ccircumflex": "C+circumflex.uc@top",
	"ccircumflex": "c+circumflex@top",
	"Cdotaccent": "C+dotaccent.uc@top",
	"cdotaccent": "c+dotaccent@top",
	"dcaron": "d+caron.alt@caron.alt",
	"Dcaron": "D+caron.uc@top",
	"Eacute": "E+acute.uc@top",
	"eacute": "e+acute@top",
	"Ebreve": "E+breve.uc@top",
	"ebreve": "e+breve@top",
	"Ecaron": "E+caron.uc@top",
	"ecaron": "e+caron@top",
	"Ecircumflex": "E+circumflex.uc@top",
	"ecircumflex": "e+circumflex@top",
	"Ecircumflexacute": "E+circumflex_acute.uc@top",
	"ecircumflexacute": "e+circumflex_acute@top",
	"Ecircumflexdotbelow": "E+circumflex.uc@top+dotbelow.uc@bottom",
	"ecircumflexdotbelow": "e+circumflex@top+dotbelow@bottom",
	"Ecircumflexgrave": "E+circumflex_grave.uc@top",
	"ecircumflexgrave": "e+circumflex_grave@top",
	"Ecircumflexhookabove": "E+circumflex_hookabove.uc@top",
	"ecircumflexhookabove": "e+circumflex_hookabove@top",
	"Ecircumflextilde": "E+circumflex_tilde.uc@top",
	"ecircumflextilde": "e+circumflex_tilde@top",
	"Edblgrave": "E+dblgrave.uc@top",
	"edblgrave": "e+dblgrave@top",
	"Edieresis": "E+dieresis.uc@top",
	"edieresis": "e+dieresis@top",
	"Edotaccent": "E+dotaccent.uc@top",
	"edotaccent": "e+dotaccent@top",
	"Edotbelow": "E+dotbelow.uc@bottom",
	"edotbelow": "e+dotbelow@bottom",
	"Egrave": "E+grave.uc@top",
	"egrave": "e+grave@top",
	"Ehookabove": "E+hookabove.uc@top",
	"ehookabove": "e+hookabove@top",
	"Einvertedbreve": "E+breveinverted.uc@top",
	"einvertedbreve": "e+breveinverted@top",
	"Emacron": "E+macron.uc@top",
	"emacron": "e+macron@top",
	#"Eogonek": "E+ogonek.uc",
	#"eogonek": "e+ogonek",
	"Etilde": "E+tilde.uc@top",
	"etilde": "e+tilde@top",
	"Gbreve": "G+breve.uc@top",
	"gbreve": "g+breve@top",
	"Gcaron": "G+caron.uc@top",
	"gcaron": "g+caron@top",
	"Gcircumflex": "G+circumflex.uc@top",
	"gcircumflex": "g+circumflex@top",
	"Gcommaaccent": "G+commaaccent.uc@bottom",
	"gcommaaccent": "g+commaturnedabove@top",
	"Gdotaccent": "G+dotaccent.uc@top",
	"gdotaccent": "g+dotaccent@top",
	"Hcircumflex": "H+circumflex.uc@top",
	"hcircumflex": "h+circumflex@top",
	"Iacute": "I+acute.uc@top",
	"iacute": "idotless+acute@top",
	"Ibreve": "I+breve.uc@top",
	"ibreve": "idotless+breve@top",
	"Icircumflex": "I+circumflex.uc@top",
	"icircumflex": "idotless+circumflex@top",
	"Idblgrave": "I+dblgrave.uc@top",
	"idblgrave": "idotless+dblgrave@top",
	"Idieresis": "I+dieresis.uc@top",
	"idieresis": "idotless+dieresis@top",
	"Idotaccent": "I+dotaccent.uc@top",
	"idotaccent": "idotless+dotaccent@top",
	"Idotbelow": "I+dotbelow.uc@bottom",
	"idotbelow": "i+dotbelow@bottom",
	"Igrave": "I+grave.uc@top",
	"igrave": "idotless+grave@top",
	"Ihookabove": "I+hookabove.uc@top",
	"ihookabove": "idotless+hookabove@top",
	"Iinvertedbreve": "I+breveinverted.uc@top",
	"iinvertedbreve": "idotless+breveinverted@top",
	"Imacron": "I+macron.uc@top",
	"imacron": "idotless+macron@top",
	#"Iogonek": "I+ogonek.uc",
	#"iogonek": "i+ogonek",
	"Itilde": "I+tilde.uc@top",
	"itilde": "idotless+tilde@top",
	"Jcircumflex": "J+circumflex.uc@top",
	"jcircumflex": "jdotless+circumflex@top",
	"Kcommaaccent": "K+commaaccent.uc@bottom",
	"kcommaaccent": "k+commaaccent@bottom",
	"Lacute": "L+acute.uc@top",
	"lacute": "l+acute@top",
	"Lcaron": "L+caron.alt@caron.alt",
	"lcaron": "l+caron.alt@caron.alt",
	"Lcommaaccent": "L+commaaccent.uc@bottom",
	"lcommaaccent": "l+commaaccent@bottom",
	#"Ldot": "L+dotaccent",
	#"ldot": "l+dotaccent",
	"Nacute": "N+acute.uc@top",
	"nacute": "n+acute@top",
	"Ncaron": "N+caron.uc@top",
	"ncaron": "n+caron@top",
	"Ncommaaccent": "N+commaaccent.uc@bottom",
	"ncommaaccent": "n+commaaccent@bottom",
	"Ntilde": "N+tilde.uc@top",
	"ntilde": "n+tilde@top",
	"Oacute": "O+acute.uc@top",
	"oacute": "o+acute@top",
	"Obreve": "O+breve.uc@top",
	"obreve": "o+breve@top",
	"Ocircumflex": "O+circumflex.uc@top",
	"ocircumflex": "o+circumflex@top",
	"Ocircumflexacute": "O+circumflex_acute.uc@top",
	"ocircumflexacute": "o+circumflex_acute@top",
	"Ocircumflexdotbelow": "O+circumflex.uc@top+dotbelow.uc@bottom",
	"ocircumflexdotbelow": "o+circumflex@top+dotbelow@bottom",
	"Ocircumflexgrave": "O+circumflex_grave.uc@top",
	"ocircumflexgrave": "o+circumflex_grave@top",
	"Ocircumflexhookabove": "O+circumflex_hookabove.uc@top",
	"ocircumflexhookabove": "o+circumflex_hookabove@top",
	"Ocircumflextilde": "O+circumflex_tilde.uc@top",
	"ocircumflextilde": "o+circumflex_tilde@top",
	"Odblgrave": "O+dblgrave.uc@top",
	"odblgrave": "o+dblgrave@top",
	"Odieresis": "O+dieresis.uc@top",
	"odieresis": "o+dieresis@top",
	"Odieresismacron": "O+dieresis_macron.uc@top",
	"odieresismacron": "o+dieresis_macron@top",
	"Odotaccentmacron": "O+dotaccent_macron.uc@top",
	"odotaccentmacron": "o+dotaccent_macron@top",
	"Odotbelow": "O+dotbelow.uc@bottom",
	"odotbelow": "o+dotbelow@bottom",
	"Ograve": "O+grave.uc@top",
	"ograve": "o+grave@top",
	"Ohookabove": "O+hookabove.uc@top",
	"ohookabove": "o+hookabove@top",
	#"Ohorn": "O+horn.uc",
	#"ohorn": "o+horn",
	"Ohornacute": "Ohorn+acute.uc@top",
	"ohornacute": "ohorn+acute@top",
	"Ohorndotbelow": "Ohorn+dotbelow.uc@bottom",
	"ohorndotbelow": "ohorn+dotbelow@bottom",
	"Ohorngrave": "Ohorn+grave.uc@top",
	"ohorngrave": "ohorn+grave@top",
	"Ohornhookabove": "Ohorn+hookabove.uc@top",
	"ohornhookabove": "ohorn+hookabove@top",
	"Ohorntilde": "Ohorn+tilde.uc@top",
	"ohorntilde": "ohorn+tilde@top",
	"Ohungarumlaut": "O+hungarumlaut.uc@top",
	"ohungarumlaut": "o+hungarumlaut@top",
	"Oinvertedbreve": "O+breveinverted.uc@top",
	"oinvertedbreve": "o+breveinverted@top",
	"Omacron": "O+macron.uc@top",
	"omacron": "o+macron@top",
	#"Oogonek": "O+ogonek.uc",
	#"oogonek": "o+ogonek",
	"Oslashacute": "Oslash+acute.uc@top",
	"oslashacute": "oslash+acute@top",
	"Otilde": "O+tilde.uc@top",
	"otilde": "o+tilde@top",
	"Otildemacron": "O+tilde_macron.uc@top",
	"otildemacron": "o+tilde_macron@top",
	"Racute": "R+acute.uc@top",
	"racute": "r+acute@top",
	"Rcaron": "R+caron.uc@top",
	"rcaron": "r+caron@top",
	"Rcommaaccent": "R+commaaccent.uc@bottom",
	"rcommaaccent": "r+commaaccent@bottom",
	"Rdblgrave": "R+dblgrave.uc@top",
	"rdblgrave": "r+dblgrave@top",
	"Rinvertedbreve": "R+breveinverted.uc@top",
	"rinvertedbreve": "r+breveinverted@top",
	"Sacute": "S+acute.uc@top",
	"sacute": "s+acute@top",
	"Scaron": "S+caron.uc@top",
	"scaron": "s+caron@top",
	"Scedilla": "S+cedilla@bottom",
	"scedilla": "s+cedilla@bottom",
	"Scircumflex": "S+circumflex.uc@top",
	"scircumflex": "s+circumflex@top",
	"Scommaaccent": "S+commaaccent.uc@bottom",
	"scommaaccent": "s+commaaccent@bottom",
	"tcaron": "t+caron.alt@caron.alt",
	"Tcaron": "T+caron.uc@top",
	"Tcedilla": "T+cedilla@bottom",
	"tcedilla": "t+cedilla@bottom",
	"Tcommaaccent": "T+commaaccent.uc@bottom",
	"tcommaaccent": "t+commaaccent@bottom",
	"Uacute": "U+acute.uc@top",
	"uacute": "u+acute@top",
	"Ubreve": "U+breve.uc@top",
	"ubreve": "u+breve@top",
	"Ucircumflex": "U+circumflex.uc@top",
	"ucircumflex": "u+circumflex@top",
	"Udblgrave": "U+dblgrave.uc@top",
	"udblgrave": "u+dblgrave@top",
	"Udieresis": "U+dieresis.uc@top",
	"udieresis": "u+dieresis@top",
	"Udotbelow": "U+dotbelow.uc@bottom",
	"udotbelow": "u+dotbelow@bottom",
	"Ugrave": "U+grave.uc@top",
	"ugrave": "u+grave@top",
	"Uhookabove": "U+hookabove.uc@top",
	"uhookabove": "u+hookabove@top",
	#"Uhorn": "hornU+horn.uc",
	#"uhorn": "hornu+horn",
	"Uhornacute": "Uhorn+acute.uc@top",
	"uhornacute": "uhorn+acute@top",
	"Uhorndotbelow": "Uhorn+dotbelow.uc@bottom",
	"uhorndotbelow": "uhorn+dotbelow@bottom",
	"Uhorngrave": "Uhorn+grave.uc@top",
	"uhorngrave": "uhorn+grave@top",
	"Uhornhookabove": "Uhorn+hookabove.uc@top",
	"uhornhookabove": "uhorn+hookabove@top",
	"Uhorntilde": "Uhorn+tilde.uc@top",
	"uhorntilde": "uhorn+tilde@top",
	"Uhungarumlaut": "U+hungarumlaut.uc@top",
	"uhungarumlaut": "u+hungarumlaut@top",
	"Uinvertedbreve": "U+breveinverted.uc@top",
	"uinvertedbreve": "u+breveinverted@top",
	"Umacron": "U+macron.uc@top",
	"umacron": "u+macron@top",
	#"Uogonek": "U+ogonek.uc",
	#"uogonek": "u+ogonek",
	"Uring": "U+ring.uc@top",
	"uring": "u+ring@top",
	"Utilde": "U+tilde.uc@top",
	"utilde": "u+tilde@top",
	"Wacute": "W+acute.uc@top",
	"wacute": "w+acute@top",
	"Wcircumflex": "W+circumflex.uc@top",
	"wcircumflex": "w+circumflex@top",
	"Wdieresis": "W+dieresis.uc@top",
	"wdieresis": "w+dieresis@top",
	"Wgrave": "W+grave.uc@top",
	"wgrave": "w+grave@top",
	"Yacute": "Y+acute.uc@top",
	"yacute": "y+acute@top",
	"Ycircumflex": "Y+circumflex.uc@top",
	"ycircumflex": "y+circumflex@top",
	"Ydieresis": "Y+dieresis.uc@top",
	"ydieresis": "y+dieresis@top",
	"Ydotbelow": "Y+dotbelow.uc@bottom",
	"ydotbelow": "y+dotbelow@bottom",
	"Ygrave": "Y+grave.uc@top",
	"ygrave": "y+grave@top",
	"Yhookabove": "Y+hookabove.uc@top",
	"yhookabove": "y+hookabove@top",
	"Ymacron": "Y+macron.uc@top",
	"ymacron": "y+macron@top",
	"Ytilde": "Y+tilde.uc@top",
	"ytilde": "y+tilde@top",
	"Zacute": "Z+acute.uc@top",
	"zacute": "z+acute@top",
	"Zcaron": "Z+caron.uc@top",
	"zcaron": "z+caron@top",
	"Zdotaccent": "Z+dotaccent.uc@top",
	"zdotaccent": "z+dotaccent@top",
}

def buildComposites(font, composites):
	for glyphName in composites.keys():
		font.newGlyph(glyphName)
		composite = font[glyphName]
		
		value = composites[glyphName]
		items = value.split("+")
		base = items[0]
		items = items[1:]

		baseGlyph = font[base]
		composite.appendComponent(base)
		composite.width = baseGlyph.width
		
		baseOffset = baseGlyph.width/2
		for item in items:
			baseName, anchorName = item.split("@")
			itemOffset = font[baseName].width/2
			# if anchors, use for offset
			anchor = None
			for a in baseGlyph.anchors:
				if a.name == anchorName:
					anchor = a
			if anchor:
				x = anchor.x - itemOffset
				y = 0 # ignore y position
				offset = (x, y)
				composite.mark = (1, 0, 0, 0.5) # pink
			else:
				# get baseGlyph center as anchor, minus itemGlyph center
				offset = (baseOffset-itemOffset, 0)
				composite.mark = (0, 0, 0, 0.5) # grey
			composite.appendComponent(baseName, offset)
		
	
buildComposites(font, composites)
